name: set-environment
author: ziro
description: 'Use set-environment module in github action'
inputs:
  REF_TYPE:
    description: 'branch or tag'
    required: true
    default: 'branch'
  BASE_REF:
    description: 'dev or master'
    required: true
    default: 'dev'
outputs:
  environment:
    description: 'set env'
    value: ${{ steps.set-env.outputs.environment }}

runs:
  using: "composite"
  steps:
  - name: set env
    id: set-env
    shell: bash
    run: |
      if [[ ${{ github.ref_type }} == "tag" ]]; then
        echo "environment=qa" >> $GITHUB_OUTPUT
        exit 0
      fi
      if [[ ${{ github.ref_type }} == "branch" ]]; then
        echo "environment=dev" >> $GITHUB_OUTPUT
        if [[ ${{ github.base_ref }} == "master" ]]; then
          echo "environment=staging" >> $GITHUB_OUTPUT
        fi
      fi
  - name: check env
    shell: bash
    run: echo ${{ steps.set-env.outputs.environment }}
