name: image build
author: ziro
description: 'Use image build module in github action'
inputs:
  REPOSITORY:
    description: 'set aws ecr repository'
    required: true
    default: 'my-app'
  REGISTRY:
    description: 'set aws ecr registry'
    required: true
    default: ''
  DOCKERFILE_PATH:
    description: 'set dockerfile path'
    required: true
    default: 'Dockerfile'

runs:
  using: "composite"
  steps:
  - name: Login to Amazon ECR
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v2
    with:
      mask-password: 'true'
  - name: docker build & push
    shell: bash
    run: |
      docker build -f ${{ inputs.DOCKERFILE_PATH }} --tag ${{ inputs.REGISTRY }}/${{ inputs.REPOSITORY }}:${{ github.sha }} .
      docker push ${{ inputs.REGISTRY }}/${{ inputs.REPOSITORY }}:${{ github.sha }}